In [32]:
using Plots; plotly();

In [2]:
f = x -> -2x[1]^2 + x[1]*x[2]^2 + 4x[1]^4

(::#1) (generic function with 1 method)

In [3]:
f([0,0])

0

In [4]:
x1 = x2 = -1:.01:1
z = Surface( (x1,x2)-> f([x1,x2]), x1, x2 )
contour(x1,x2,z,levels=50)

In [5]:
surface(x1,x2,z,levels=50)

In [6]:
using Polynomials

INFO: Recompiling stale cache file /Users/mpf/.julia/lib/v0.6/Polynomials.ji for module Polynomials.


In [7]:
p = poly( [-4, -2, -1, 1, 3] )

Poly(24 + 10*x - 27*x^2 - 11*x^3 + 3*x^4 + x^5)

In [8]:
xlim = (-4.1, 3.1)
plot( t->p(t), xlim... )
r = roots(p)
scatter!(r, zeros(r))

In [9]:
function gen_data(p, m, η)
   srand(0)
   t = randn(m)
   noise = randn(m); noise *= η/norm(noise)
   b = p(t) + noise
   return (t,b)
end

gen_data (generic function with 1 method)

In [10]:
# Generate random data
t = b = []
m = 100 # no. of samples
η = 20 # % of noise
t, b = gen_data(p, m, η);
scatter( t, b, xlim=xlim, ylim=(-100,60) )

In [11]:
# Compute polynomial fit
d = 3 # degree of fit
pp = polyfit(t,b,d)
scatter( t, b, xlim=xlim, ylim=(-100,60) )
plot!( t->pp(t), xlim... )

In [12]:
d = 5
A = [ t[i]^k for i=1:m, k=0:d ]
x = A \ b # == inv(A)*b
pp = Poly(x)
plot!( t->pp(t), xlim..., ylim=(-100,60) )

In [13]:
x1 = A \ b
x2 = (A'A) \ (A'b)
norm(x1 - x2)

9.58472872582309e-13

In [14]:
A = randn(3,2)

3×2 Array{Float64,2}:
  1.21158     1.26059 
  0.0927033  -1.42516 
 -1.2736      0.321342

In [15]:
Q, R = qr(A);
Q

3×2 Array{Float64,2}:
 -0.68829     0.473903
 -0.0526641  -0.787772
  0.723522    0.393486

In [16]:
Q'*Q

2×2 Array{Float64,2}:
 1.0          4.35144e-17
 4.35144e-17  1.0        

In [17]:
R

2×2 Array{Float64,2}:
 -1.76028  -0.560101
  0.0       1.84654 

In [18]:
b = rand(3)
# Ax = b
x1 = A\b
x2 = R \ (Q'b)
norm(x1-x2)

3.469446951953614e-16

In [19]:
size(A)

(3, 2)

In [20]:
Q

3×2 Array{Float64,2}:
 -0.68829     0.473903
 -0.0526641  -0.787772
  0.723522    0.393486

In [21]:
R

2×2 Array{Float64,2}:
 -1.76028  -0.560101
  0.0       1.84654 

In [22]:
Q, R = qr(A)
Q

3×2 Array{Float64,2}:
 -0.68829     0.473903
 -0.0526641  -0.787772
  0.723522    0.393486

In [23]:
R

2×2 Array{Float64,2}:
 -1.76028  -0.560101
  0.0       1.84654 

In [24]:
Q, R = qr(A, thin=false)

([-0.68829 0.473903 0.549248; -0.0526641 -0.787772 0.613711; 0.723522 0.393486 0.567173], [-1.76028 -0.560101; 0.0 1.84654])

In [25]:
Q

3×3 Array{Float64,2}:
 -0.68829     0.473903  0.549248
 -0.0526641  -0.787772  0.613711
  0.723522    0.393486  0.567173

In [26]:
Q*Q'

3×3 Array{Float64,2}:
  1.0          -1.11022e-16  -5.55112e-17
 -1.11022e-16   1.0          -1.11022e-16
 -5.55112e-17  -1.11022e-16   1.0        

In [27]:
R

2×2 Array{Float64,2}:
 -1.76028  -0.560101
  0.0       1.84654 

In [28]:
R = [R; zeros(1,2)]

3×2 Array{Float64,2}:
 -1.76028  -0.560101
  0.0       1.84654 
  0.0       0.0     

In [29]:
size(A)

(3, 2)

In [30]:
A - Q*R

3×2 Array{Float64,2}:
 -2.22045e-16   0.0        
  0.0           2.22045e-16
 -2.22045e-16  -1.66533e-16

In [31]:
Q, R = [A b]

3×3 Array{Float64,2}:
  1.21158     1.26059   0.860951
  0.0927033  -1.42516   0.910171
 -1.2736      0.321342  0.310106