In [1]:
using Plots; gr()

Plots.GRBackend()

In [2]:
f = x -> -2x[1]^2 + x[1]*x[2]^2 + 4x[1]^4;

In [3]:
f([0,0])

0

In [4]:
x1 = x2 = -1:.01:1
z = Surface( (x1,x2)-> f([x1,x2]), x1, x2 )
contour(x1,x2,z,levels=50)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
<polyline clip-path="url(#clip1002)" style="stroke:#a52c5f; stroke-width:1; stroke-opacity:1; fill:none" points="
 41.2581,375.813 41.5494,374.607 41.7036,373.993 42.1549,372.173 42.5999,370.353 43.0387,368.533 43.4713,366.713 43.8979,364.893 43.9553,364.645 44.3337,363.073 
 44.7655,361.253 45.1912,359.433 45.6107,357.613 46.024,355.793 46.3612,354.287 46.4343,353.973 46.8525,352.153 47.2645,350.333 47.6703,348.513 48.07,346.693 
 48.4636,344.873 48.767,343.449 48.8547,343.053 49.2525,341.233 49.6441,339.413 50.0295,337.593 50.4088,335.773 50.782,333.953 51.1493,332.133 51.1729,332.014 
 51.525,330.313 51.8956,328.493 52.2601,326.673 52.6184,324.853 52.9707,323.033 53.317,321.213 53.5787,319.814 53.6607,319.393 54.0097,317.573 54.3524,315.753 
 54.6891,313.933 55.0197,312.113 55.3444,310.293 55.6631,308.473 55.9759,306.653 55.9846,306.601 56.2958,304.833 56.61,303.013 56.9182,301.193 57.2204,299.373 
 57.5166,297.553 57.8069,295.733 58.0913,293.913 58.3699,292.093 58.3904,291.956 58.6538,290.273 58.9326,288.453 59.2053,286.633 59.4722,284.813 59.7331,282.993 
 59.9881,281.173 60.2373,279.353 60.4808,277.533 60.7184,275.713 60.7963,275.102 60.9572,273.893 61.1935,272.073 61.4239,270.253 61.6483,268.433 61.867,266.613 
 62.0798,264.793 62.2868,262.973 62.4881,261.153 62.6836,259.333 62.8734,257.513 63.0576,255.693 63.2022,254.219 63.2377,253.873 63.4184,252.053 63.5932,250.233 
 63.7622,248.413 63.9254,246.593 64.0829,244.773 64.2346,242.953 64.3805,241.133 64.5208,239.313 64.6555,237.493 64.7844,235.673 64.9078,233.853 65.0255,232.032 
 65.1376,230.212 65.2441,228.392 65.3451,226.572 65.4406,224.752 65.5305,222.932 65.608,221.26 65.6152,221.112 65.6976,219.292 65.7743,217.472 65.8453,215.652 
 65.9105,213.832 65.9701,212.012 66.0239,210.192 66.0721,208.372 66.1146,206.552 66.1514,204.732 66.1825,202.912 66.2079,201.092 66.2277,199.272 66.2419,197.452 
 66.2504,195.632 66.2532,193.812 66.2504,191.992 66.2419,190.172 66.2277,188.352 66.2079,186.532 66.1825,184.712 66.1514,182.892 66.1146,181.072 66.0721,179.252 
 66.0239,177.432 65.9701,175.612 65.9105,173.792 65.8453,171.972 65.7743,170.152 65.6976,168.332 65.6152,166.512 65.608,166.364 65.5305,164.692 65.4406,162.872 
 65.3451,161.052 65.2441,159.232 65.1376,157.412 65.0255,155.592 64.9078,153.772 64.7844,151.952 64.6555,150.132 64.5208,148.312 64.3805,146.492 64.2346,144.672 
 64.0829,142.852 63.9254,141.032 63.7622,139.212 63.5932,137.392 63.4184,135.572 63.2377,133.752 63.2022,133.405 63.0576,131.932 62.8734,130.112 62.6836,128.292 
 62.4881,126.472 62.2868,124.652 62.0798,122.832 61.867,121.012 61.6483,119.192 61.4239,117.372 61.1935,115.552 60.9572,113.732 60.7963,112.522 60.7184,111.912 
 60.4808,110.092 60.2373,108.272 59.9881,106.452 59.7331,104.632 59.4722,102.812 59.2053,100.992 58.9326,99.1716 58.6538,97.3516 58.3904,95.6686 58.3699,95.5316 
 58.0913,93.7116 57.8069,91.8916 57.5166,90.0715 57.2204,88.2515 56.9182,86.4315 56.61,84.6115 56.2958,82.7915 55.9846,81.0232 55.9759,80.9715 55.6631,79.1515 
 55.3444,77.3315 55.0197,75.5114 54.6891,73.6914 54.3524,71.8714 54.0097,70.0514 53.6607,68.2314 53.5787,67.8106 53.317,66.4114 52.9707,64.5914 52.6184,62.7714 
 52.2601,60.9514 51.8956,59.1313 51.525,57.3113 51.1729,55.61 51.1493,55.4913 50.782,53.6713 50.4088,51.8513 50.0295,50.0313 49.6441,48.2113 49.2525,46.3913 
 48.8547,44.5712 48.767,44.1758 48.4636,42.7512 48.07,40.9312 47.6703,39.1112 47.2645,37.2912 46.8525,35.4712 46.4343,33.6512 46.3612,33.3371 46.024,31.8312 
 45.6107,30.0111 45.1912,28.1911 44.7655,26.3711 44.3337,24.5511 43.9553,22.979 43.8979,22.7311 43.4713,20.9111 43.0387,19.0911 42.5999,17.2711 42.1549,15.451 
 41.7036,13.631 41.5494,13.0172 41.2581,11.811 
 "/>
<polyline clip-path="url(#clip1002)" style="stroke:#ad305b; stroke-width:

In [5]:
surface(x1,x2,z,levels=50)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip1200)" style="stroke:#000000; stroke-width:1; stroke-opacity:1; fill:none" points="
 127.728,354.311 127.728,354.311 125.869,355.388 127.728,354.311 127.728,319.562 126.799,320.101 127.728,319.562 127.728,284.813 125.869,285.89 127.728,284.813 
 127.728,250.064 126.799,250.603 127.728,250.064 127.728,215.315 125.869,216.392 127.728,215.315 127.728,180.566 126.799,181.105 127.728,180.566 127.728,145.817 
 125.869,146.895 127.728,145.817 127.728,111.068 126.799,111.607 127.728,111.068 127.728,76.3192 125.869,77.3967 127.728,76.3192 
 "/>
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip1200)" style="stroke:#000000; stroke-width:1; stroke-opacity:1; fill:none" points="
 127.728,354.311 127.728,354.311 125.869,355.388 127.728,354.311 151.819,356.999 150.89,357.537 151.819,356.999 175.911,359.686 174.052,360.764 175.911,359.686 
 200.002,362.374 199.072,362.913 200.002,362.374 224.093,365.062 222.234,366.14 224.093,365.062 248.184,367.75 247.255,368.289 248.184,367.75 272.275,370.438 
 270.417,371.515 272.275,370.438 296.367,373.126 295.437,373.664 296.367,373.126 320.458,375.813 318.599,376.891 320.458,375.813 
 "/>
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip1200)" style="stroke:#000000; stroke-width:1; stroke-opacity:1; fill:none" points="
 320.458,375.813 320.458,375.813 324.312,376.244 320.458,375.813 334.367,367.75 336.294,367.965 334.367,367.75 348.276,359.686 352.131,360.116 348.276,359.686 
 362.185,351.623 364.112,351.838 362.185,351.623 376.094,343.559 379.949,343.989 376.094,343.559 390.003,335.496 391.931,335.711 390.003,335.496 403.912,327.432 
 407.767,327.862 403.912,327.432 417.821,319.369 419.749,319.584 417.821,319.369 431.73,311.305 435.585,311.735 431.73,311.305 
 "/>
 
<image width="304" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAATAAAAFsCAYAAABLt+V/AAAgAElEQVR4nOy9e7Rny1Ee9vXvjuJc
6UoXMMi8weYVUHgJbEQAE55WRECWFhDAGAUMChAusklMWE4AL4fFCiCCedkKBosQTHgsMBhIvAjY
Bi0SrABmGTAOL4OReT+M7tWV7szZXfmju6q+qu59zpmZMzPnd07XrDO/vXv3a3dXf11VXd27iAgW
LVq06Bjp8KArsGjRokV3SgvAFi1adLS0AGzRokVHSwvAFi1adLS0AGzRokVHSwvAFi1adLS0AGzR
okVHSwvAFi1adLS0AGzRokVHSwvAFi1adLS0AGzRokVHSwvAFi1adLS0AGzRokVHSwvAFi1adLS0
AGzRokVHSwvAFi1adLS0AGzRokVHSwvAFi1adLS0AGzRokVHSwvAFi1adLS0AGzRokVHSwvAFi1a
dLS0AGzRokVHSwvAFi1adLS0AGzRokVHSU/deoUsAFu0aNFxkmxLAlu0aNFxUq1PLQBbtGjR8dHr
n/oakSWBLVq06ChJNohsuPGg67Fo0aJFt0Ove/LLpAB4xtO/oCwAW7Ro0XGRbAAEAJYEtmjRoiMj
2SALwBYtWnSUVG8uAFu0aNHx0eOPf7EU2SCoABaALVq06JhouwmRk24HW1uJFi1adERUZGvgVReA
LVq06NhIToC6NSDDUiEXLVp0JPT4H36elO1ml8BOACwAW7Ro0RHQ47//uYJSILKh1K1JYlgAtmjR
omOgugGltF/ZAFmrkIsWLToWqicoEKDeAuotPPLW31qABWCLFi06AirYAJEmeXXpC1gAtmjRoktO
T/zmpwlQzX2ibLfs2QKwRYsWXW6SBl5Fpa8lgS1atOhoSMhwX7cFYIsWLToOeuI1f0nK5gBW6oan
v8P3Fn2+AGzRokWXkp74jU+SIoIiG6SDl24hUloAtmjRostJUvvKo9u/CqmPwAKwRYsWXVIq2y0U
kbZtSDag1iWBLVq06EiIVh1dAlsAtmjRoktOT/7qX5Rm8+qgtXU1sm/iVloAtmjRostHtRntpdYg
iUEkRFsAtmjRostHpDo2yWsZ8RctWnQE9OQvfpSUeoJSTwy42m835BMtAFu0aNGloSf/vxeISVyV
JK86biMC1pHSixYtukQUVhtrXIGEVPyJ93l14fhLAlu0aNHloe77VeoJsJ00o33dmj9YcqEAFoAt
WrToElEx73taddT7ZP8CFoAtWrToktAbfvY/FTttYmsf7igKXts22L+ABWCLFi26LCRbMNaXWgFI
d2ZdEtiiRYsuM/FKo0piguAHlmkB2KJFix44PfUv3l9Kd5soUpsBX433uol7SWCLFi26bPTUT7+/
qKE+qJAGXtVtYYkWgC1atOjBUl9tLOZt36/ZD6xWoMqQdAHYokWLHizZuV9NVSzkhW9OrNuGGx/5
6yUnXQC2aNGiB0Y3X/0+Uiqpj9V9v3zlUab2L2AB2KJFix4Q3fyJ9xQIoptE3VydVMO9SPMDm9AC
sEWLFj0YquLGeTXim+e9NJuXiIdNaAHYokWLHgiV7uelUlZQIcMxOgvAFi1adIno1qveTcxRtVYI
H6HTN3C3U1nb/UMf8zuDAR9YALZo0aIHQVJNRYxHRpPEZWA2l76ABWCLFi16ENSdU0XEHVWr27+K
+n0p0O3QArBFixbdV7r1z95F9HSJIrCVRwWsItK2Em0kie3QArBFixbdN7r1T99JCtBtXgmgstHe
jPxLAlu0aNEloNL9ucq2JRVR0L4Die55T8fn1LkPGLAAbNGiRfeT2HWiCgoEIqMNDNkfbIcWgC1a
tOi+0MkPvX07dQKsIk7AyvZFUvgOLQBbtGjR/aFtA1BRqkDIx6sIXG1UwNr6RzxqWRLYokWLHiyd
/OO3FdugLUCpZLyvrCqyFAaICG685MmpEyuwAGzRokX3g+z7jh2gwmojkipZIRUo+94TRg

In [6]:
using Polynomials

In [7]:
p = poly( [-4, -2, -1, 1, 3] )

Poly(24 + 10*x - 27*x^2 - 11*x^3 + 3*x^4 + x^5)

In [8]:
xlim = (-4.1, 3.1)
plot( t->p(t), xlim... )
r = roots(p)
scatter!(r, zeros(r))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 -75 
 
 
 -50 
 
 
 -25 
 
 
 0 
 
 
 25 
 
 
 50 
 
<polyline clip-path="url(#clip1402)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 51.2582,210.748 52.5193,199.919 53.7805,189.5 55.0416,179.482 57.9568,157.816 60.8721,138.148 63.7873,120.381 66.7026,104.417 69.6178,90.1635 72.5331,77.5297 
 75.4483,66.4274 78.3636,56.7709 81.2788,48.4771 84.1941,41.4657 87.1093,35.6585 90.0246,30.9799 92.9398,27.3569 95.8551,24.7187 98.7703,22.9968 101.686,22.1253 
 105.189,22.113 108.693,23.1306 112.197,25.0763 115.701,27.8529 122.709,35.5317 129.717,45.4769 141.567,65.7383 153.417,88.1324 166.289,112.436 179.161,134.697 
 185.095,143.835 191.029,152.102 196.962,159.413 202.896,165.702 209.257,171.26 215.619,175.561 221.98,178.6 228.342,180.39 235.712,180.95 243.082,179.967 
 250.453,177.559 257.823,173.867 270.923,164.665 284.023,153.025 295.51,141.77 306.997,130.448 319.522,119.074 332.046,109.806 338.345,106.279 344.645,103.678 
 350.944,102.119 357.243,101.707 364.208,102.695 371.173,105.302 378.138,109.607 385.102,115.667 391.729,123.087 398.356,132.117 404.983,142.727 411.609,154.857 
 418.5,168.985 425.39,184.517 432.28,201.271 439.171,219.022 450.771,250.38 462.371,282.151 469.453,300.893 476.534,318.49 483.616,334.327 490.697,347.722 
 494.025,352.962 497.354,357.413 500.682,360.987 504.01,363.592 507.339,365.133 510.667,365.511 513.995,364.623 517.324,362.361 519.99,359.484 522.656,355.594 
 525.322,350.632 527.988,344.534 530.654,337.236 533.321,328.671 535.987,318.773 538.653,307.47 541.319,294.692 543.985,280.364 546.651,264.411 549.317,246.755 
 551.983,227.318 554.65,206.017 557.316,182.77 559.982,157.491 561.623,140.881 563.264,123.448 564.906,105.169 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 
 y2

In [9]:
function gen_data(p, m, η)
   srand(0)
   t = randn(m)
   noise = randn(m); noise *= η/norm(noise)
   b = p(t) + noise
   return (t,b)
end

gen_data (generic function with 1 method)

In [10]:
# Generate random data
t = b = []
m = 100 # no. of samples
η = 20 # % of noise
t, b = gen_data(p, m, η);
scatter( t, b, xlim=xlim, ylim=(-100,60) )

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 -100 
 
 
 -50 
 
 
 0 
 
 
 50 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [11]:
# Compute polynomial fit
d = 3 # degree of fit
pp = polyfit(t,b,d)
scatter( t, b, xlim=xlim, ylim=(-100,60) )
plot!( t->pp(t), xlim... )

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 -100 
 
 
 -50 
 
 
 0 
 
 
 50 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip1802)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 43.7516,-130.08 45.0648,-124.551 46.378,-119.09 47.6912,-113.697 59.8336,-66.9699 71.9761,-25.702 84.1185,10.4058 96.261,41.6526 110.855,73.199 125.449,98.6747 
 137.789,115.862 150.128,129.396 163.532,140.322 176.935,147.709 189.293,151.73 201.65,153.401 228.146,150.527 258.845,139.586 286.126,126.728 310.049,115.819 
 336.132,107.122 362.37,104.653 376.875,107.091 391.379,112.885 405.18,121.978 418.981,135.009 433.33,153.206 447.68,176.63 459.759,200.762 471.839,229.242 
 486.586,270.335 501.334,318.884 508.265,344.431 515.197,371.798 522.128,401.043 529.06,432.219 540.164,486.334 551.269,545.78 562.374,610.786 573.479,681.581 
 575.188,693.004 576.897,704.571 578.606,716.283 
 "/>
 
 
 
 
 
 y1 
 
 
 
 y2

In [12]:
d = 5
A = [ t[i]^k for i=1:m, k=0:d ]
x = A \ b # == inv(A)*b
pp = Poly(x)
plot!( t->pp(t), xlim..., ylim=(-100,60) )

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 -100 
 
 
 -50 
 
 
 0 
 
 
 50 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip2002)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 43.7516,-130.08 45.0648,-124.551 46.378,-119.09 47.6912,-113.697 59.8336,-66.9699 71.9761,-25.702 84.1185,10.4058 96.261,41.6526 110.855,73.199 125.449,98.6747 
 137.789,115.862 150.128,129.396 163.532,140.322 176.935,147.709 189.293,151.73 201.65,153.401 228.146,150.527 258.845,139.586 286.126,126.728 310.049,115.819 
 336.132,107.122 362.37,104.653 376.875,107.091 391.379,112.885 405.18,121.978 418.981,135.009 433.33,153.206 447.68,176.63 459.759,200.762 471.839,229.242 
 486.586,270.335 501.334,318.884 508.265,344.431 515.197,371.798 522.128,401.043 529.06,432.219 540.164,486.334 551.269,545.78 562.374,610.786 573.479,681.581 
 575.188,693.004 576.897,704.571 578.606,716.283 
 "/>
<polyline clip-path="url(#clip2002)" style="stroke:#3da44d; stroke-width:1; stroke-opacity:1; fill:none" points="
 43.7516,186.805 45.0648,177.246 46.378,168.051 47.6912,159.215 50.7268,140.116 53.7624,122.798 56.798,107.171 59.8336,93.1508 62.8693,80.6523 65.9049,69.5946 
 68.9405,59.8988 71.9761,51.488 75.0117,44.2882 78.0473,38.227 81.0829,33.2348 84.1185,29.244 87.1541,26.1889 90.1898,24.0064 93.2254,22.6353 96.261,22.0165 
 99.9095,22.1878 103.558,23.2684 107.207,25.1673 110.855,27.7977 118.152,34.9252 125.449,44.0345 137.789,62.4197 150.128,82.5949 163.532,104.369 176.935,124.204 
 183.114,132.309 189.293,139.616 195.471,146.051 201.65,151.558 208.274,156.387 214.898,160.08 221.522,162.632 228.146,164.061 235.821,164.355 243.495,163.266 
 251.17,160.902 258.845,157.394 272.485,148.82 286.126,138.11 298.088,127.832 310.049,117.556 323.091,107.3 336.132,99.0243 342.692,95.9157 349.251,93.6638 
 355.811,92.3723 362.37,92.1351 369.622,93.1994 376.875,95.7472 384.127,99.851 391.379,105.56 398.28,112.504 405.18,120.919 412.08,130.777 418.981,142.023 
 426.156,155.098 433.33,169.454 440.505,184.927 447.68,201.309 459.759,230.238 471.839,259.557 479.212,276.869 486.586,293.148 493.96,307.836 501.334,320.314 
 504.799,325.224 508.265,329.42 511.731,332.822 515.197,335.347 518.662,336.909 522.128,337.419 525.594,336.782 529.06,334.901 531.836,332.43 534.612,329.043 
 537.388,324.685 540.164,319.299 542.941,312.826 545.717,305.208 548.493,296.382 551.269,286.285 554.046,274.852 556.822,262.017 559.598,247.711 562.374,231.864 
 565.15,214.405 567.927,195.259 570.703,174.351 573.479,151.605 575.188,136.654 576.897,120.958 578.606,104.497 
 "/>
 
 
 
 
 
 y1 
 
 
 
 y2 
 
 
 
 y3

In [13]:
x1 = A \ b
x2 = (A'A) \ (A'b)
norm(x1 - x2)

9.58472872582309e-13

In [14]:
A = randn(3,2)

3×2 Array{Float64,2}:
 -0.50376     0.720839
  0.0646768  -0.686564
  0.907637   -0.237696

In [15]:
Q, R = qr(A);
Q

3×2 Array{Float64,2}:
 -0.484349    0.518982
  0.0621846  -0.782591
  0.872662    0.343814

In [16]:
Q'*Q

2×2 Array{Float64,2}:
  1.0          -2.44456e-16
 -2.44456e-16   1.0        

In [17]:
R

2×2 Array{Float64,2}:
 1.04008  -0.59926 
 0.0       0.829679

In [18]:
b = rand(3)
# Ax = b
x1 = A\b
x2 = R \ (Q'b)
norm(x1-x2)

1.3183898417423734e-16

In [19]:
size(A)

(3, 2)

In [20]:
Q

3×2 Array{Float64,2}:
 -0.484349    0.518982
  0.0621846  -0.782591
  0.872662    0.343814

In [21]:
R

2×2 Array{Float64,2}:
 1.04008  -0.59926 
 0.0       0.829679

In [22]:
Q, R = qr(A)
Q

3×2 Array{Float64,2}:
 -0.484349    0.518982
  0.0621846  -0.782591
  0.872662    0.343814

In [23]:
R

2×2 Array{Float64,2}:
 1.04008  -0.59926 
 0.0       0.829679

In [24]:
Q, R = qr(A, thin=false)

([-0.484349 0.518982 0.704318; 0.0621846 -0.782591 0.619422; 0.872662 0.343814 0.346774], [1.04008 -0.59926; 0.0 0.829679])

In [25]:
Q

3×3 Array{Float64,2}:
 -0.484349    0.518982  0.704318
  0.0621846  -0.782591  0.619422
  0.872662    0.343814  0.346774

In [26]:
Q*Q'

3×3 Array{Float64,2}:
  1.0          5.55112e-17  -3.88578e-16
  5.55112e-17  1.0           8.32667e-17
 -3.88578e-16  8.32667e-17   1.0        

In [27]:
R

2×2 Array{Float64,2}:
 1.04008  -0.59926 
 0.0       0.829679

In [28]:
R = [R; zeros(1,2)]

3×2 Array{Float64,2}:
 1.04008  -0.59926 
 0.0       0.829679
 0.0       0.0     

In [29]:
size(A)

(3, 2)

In [30]:
A - Q*R

3×2 Array{Float64,2}:
  1.11022e-16  -5.55112e-16
 -1.38778e-17   0.0        
 -2.22045e-16   4.71845e-16

In [31]:
Q, R = [A b]

3×3 Array{Float64,2}:
 -0.50376     0.720839  0.737199
  0.0646768  -0.686564  0.722073
  0.907637   -0.237696  0.652713